### ISSUE TITLE
Repeated chromosome indexes on the fitness array

### ISSUE THREAD

**Issue by LuisFJS04** [ceandrade/brkga_mp_ipr_python#1]
I noticed that there seems to be a problem inside `def evolve_population(self, population_index: int) -> None:`. When checking the fitness array inside `self._current_populations` I noticed that some chromosomes indexes where repeated.

For example, this is the state of fitness after 10 generations. In this case, the size of the population is 10 individuals, with 5 chromosomes each and just 1 population:

Fitness = 
(tensor(0.6850, device='cuda:0'), 8)
(tensor(0.6700, device='cuda:0'), 9)
(tensor(0.6500, device='cuda:0'), 3)
(tensor(0.5700, device='cuda:0'), 6)
(tensor(0.5650, device='cuda:0'), 2)
(tensor(0.5500, device='cuda:0'), 0)
(tensor(0.5500, device='cuda:0'), 0)
(tensor(0.5100, device='cuda:0'), 8)
(tensor(0.5100, device='cuda:0'), 7)
(tensor(0.5100, device='cuda:0'), 1)

Here, there are two different instances of the chromosome 8 and of the chromosome 0. Similarly, there are no scores for the chromosome 4 and for the chromosome 5. 

The same phenomenon can be seen in the original example provided with the code.

**Comment by ceandrade** [comment]
Thanks, @LuisFJS04, for reporting it. This looks like a serious bug, and indeed, I must check the C++ and Julia versions too. The code in Python is really low priority to me now. If you have a clue about what is happening and need this fixed ASAP, I invite you not to wait for me and submit a patch.

**Comment by ceandrade** [comment]
@LuisFJS04, just to confirm, this bug is presented only in the Python version. I cannot reproduce him either in C++ or Julia versions, after pretty extensive testing.

I have the bug fixed: instead, to rebuild the indices for the elite set, the code was just copying the old indexing. Now, we rebuild the all indices properly.
