### ISSUE TITLE
Wrong order?

### ISSUE THREAD

**Issue by LuisFJS04** [ceandrade/brkga_mp_ipr_python#2]
Mr. Carlos,

I have a question regarding evolve_population().  Specifically, after running some tests I saw how the score of one of the individuals was suddenly changed, even though the chromosomes themselves didn't change. 

I believe the problem might be on line 682 of algorithm.py. When copying the elite chromosomes, curr_pop.chromosomes has not been reordered yet so there's no guarantee that the elites are at the top of the array.

Is that the case? Before I proposed a fix for the code I wanted to confirm if I am correct.

**Comment by LuisFJS04** [comment]
Thank you for the chance to contribute. I'll make the pull request.

I'm currently testing the code, but yes, that was what I thought.

**Comment by ceandrade** [comment]
Fix merged
